buildConfig: uat
api: https://staging.talktofrank.com
ga: UA-129232-18 # @joel - update this as this is the test account
robotsDisallow: true

elasticsearch:
  #  host: 'https://search-talktofrank-elastic-beta-tsq3jroogc3kwgtk4s77uab2he.eu-west-2.es.amazonaws.com/'
  host: "https://vpc-talktofrank-uat-uralixhskpcrn5ht4p74epe4z4.eu-west-2.es.amazonaws.com/"

contentful:
  contentHost: "cdn.contentful.com"
  contentSpace: "ip74mqmfgvqf"
  contentAccessToken: !!import/single "../config.creds.yaml"
  webhookSecretKey: !!import/single "../config.webhooksecretkey.yaml"
  environment: develop

sentry:
  dsn: !!import/single "../config.sentry.yaml"
  logErrors: true

googleAPI:
  places: !!import/single "../config.google.yaml"

email:
  transport: mailgun

etherealEmail:
  auth:
    pass: !!import/single "../config.ethereal.yaml"

mailgun:
  auth:
    api_key: !!import/single "../config.mailgun.yaml"
    domain: "talktofrank.com"
