useFixtures: false
elasticsearch:
  host: 'https://search-talktofrank-elastic-beta-tsq3jroogc3kwgtk4s77uab2he.eu-west-2.es.amazonaws.com/'
  amazonES:
    region: 'eu-west-2'
  indices:
    drugNames: 'talktofrank-beta-drug-name'
    drug: 'talktofrank-beta-drug-text'
    content: 'talktofrank-beta-content'

sentry:
 logErrors: false

contentful:
  contentTypes:
    drug: 'drug'
    news: 'news'
    page: 'generalPage'
  entries:
    homepage: '6YkX4gZ5jawC0eAM6aOCum'