buildConfig: production
api: https://ttf-preview.cxp.io:3000

contentful:
  contentHost: 'preview.contentful.com'
  contentSpace: 'ip74mqmfgvqf'
  contentAccessToken: !!import/single '../config.creds.yaml'
  environment: 'develop'

sentry:
 dsn: !!import/single '../config.sentry.yaml'
 logErrors: false

basicAuth:
  username: !!import/single '../config.auth.username.yaml'
  password: !!import/single '../config.auth.password.yaml'

googleAPI:
  places: !!import/single '../config.google.yaml'